### ISSUE TITLE
Manipulating size of text

### ISSUE THREAD

**Issue by IsadoraBM** [tidymodels/corrr#144]
Can you add a label size argument?

**Comment by juliasilge** [comment]
Unfortunately not, and I find this quite frustrating myself when it comes to `autoplot()`-ish methods, as someone who customizes my plots a lot. There was supposedly some work being planned in ggplot2 that will make it easier to theme fonts and font sizes like this, but in the meantime, what I do if I really want to customize label sizes or font is:

- copy the source code of the function I am using into my script, usually in the `setup` chunk of my `.Rmd`
- change the thing I want to change, like the [size of the text being used by ggrepel](https://github.com/tidymodels/corrr/blob/master/R/cor_df.R#L278-L282), if that is what you want to change
- go about my way

This is far from ideal, we know. 😒

**Comment by IsadoraBM** [comment]
Thanks for this suggestion Julia! So I would copy all the code, right, not just from line 260?

**Comment by juliasilge** [comment]
Yes, you can check out how I did something similar in [this blog post](https://juliasilge.com/blog/datasaurus-multiclass/), where I [override the `autoplot()` method for a confusion matrix because I wanted custom colors and fonts](https://github.com/juliasilge/juliasilge.com/blob/master/content/blog/datasaurus-multiclass/index.Rmarkdown).

**Comment by juliasilge** [comment]
Let us know if you have further questions! 🙌
