### ISSUE TITLE
Error-information from corrr-package

### ISSUE THREAD

**Issue by githubtobben** [tidymodels/corrr#34]
Dr. Simon Jackson,
 
First – thanks for the nice R-package “corrr” you have made.  When I used the version 0.2.1 I run into a problem. I’m not sure whether it is a bug or I’m doing something wrong. I’m confronted with the following problem:
 
I used the following code:

rdf <- correlate(newRANG, method = "spearman")network_plot(rdf, legend = TRUE, colours = c("slategrey", "palegreen"))When I tried to visualize the relations, I got the following indication that something is wrong:

Error in calcCurveGrob(x, x$debug) : end points must not be identical

Note! I did not run into any problem when I used, method = "pearson", i.e. the plot was made correctly.
 I hope you have time to look into the problem. It will be of great help.

 Kind regards,
githubtobben

**Comment by drsimonj** [comment]
Thanks @githubtobben 
As discussed, the root of this problem was the "spearman" method resulting in perfectly correlated variables (at 1 or -1). 

The best way to handle this might be to convert perfect correlations to their `sign * .999` (or something that is close to, but avoids 1 or -1) before the layout is determined.

**Comment by juliasilge** [comment]
Thanks for this discussion! I'm going to close this older issue and see if current users report a similar problem in their typical use case.
