### ISSUE TITLE
NAs produced by integer64 overflow

### ISSUE THREAD

**Issue by justinmarschall** [tidymodels/corrr#81]
Hello,

I'm getting the `correlate()` function to return a tibble of entirely `NA` values with the warning below (note: `ordertotal` is a variable in my data, it is as good as any `x`). 

```
In `*.integer64`(((obs * ordertotal_two) - (ordertotal_sum * ordertotal_sum)),  :
  NAs produced by integer64 overflow
```

I get one warning for each variable in my table.

I am connected to an AWS Redshift database via `dbConnect()` and `odbc()`.  I'm trying to correlate three variables as a POC of this functionality.  Each variable is a numeric double.  There are 7.3 million observations in my table.

I have `corrr` version 0.4.0 installed.

This is the basic structure of the code that I'm running.

```r
# set up packages
library(odbc)
library(tidyverse)
library(dbplyr)
library(corrr)

# connect to db
redshift <- dbConnect(odbc::odbc(), "my_dsn")

# create pointer to db table
rs_table <- tbl(redshift, in_schema("my_schema", "my_table"))

# correlate
rs_table %>% 
  select(x1,
         x2,
         x3) %>% 
  correlate(quiet = TRUE)
```

I'm unsure if this is a Redshift issue, if I'm doing something incorrectly, or if there is really an issue in the `corrr` package.  Any comments on this are appreciated.

**Comment by topepo** [comment]
A new issue would be helpful. When you do, can you please provide a _minimal_ reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.
